name: okbig

channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.9
  - datasets>=2.11.0
  - deepspeed
  - gxx_linux-64=10.4.0
  - gcc
  - ninja
  - numpy
  - pandas
  - pytorch==1.13.1
  - transformers>=4.27.2
  - cudatoolkit
  - pytorch-lightning==1.9.4
  - evaluate>=0.4.0
  - rouge-score>=0.1.2